백엔드 토큰 연동
DevCommunity-ko/Front pull request #11
Opened 2022-01-29 15:32 UTC by SolKimDev

기존에 연동해두었던 네이버 API(프론트엔드) 토큰을 백엔드 API 토큰으로 대체하였습니다.
이 커밋이 머지 된 이후 기존 프론트 API는 삭제해 이용하지 못하도록 할 예정입니다.

한 가지 여쭤보고 싶은건, env 같은 환경을 설정하지 않고 소스 코드 내에 API 토큰을 raw-text로 두어도 괜찮은 걸까요??

2022-01-29 15:41 UTC, blurfx requested changes
헉 말씀해주신대로 인증 토큰같이 민감한 정보나 API 서버같이 환경에 따라 달라지는 값들은 `.env` 관리하는게 좋습니다.
원래 다음 작업으로 dotenv에서 서버 주소를 가져오는 작업을 하려고 했었는데, 이 참에 희수님이 이 PR에서 같이 해주시면 좋을 것 같아요 👀 

일단 이미 토큰이 노출되었으니 리셋이 필요할 것 같습니다.

2022-01-30 13:16 UTC, SolKimDev commented
A.  dotenv를 적용하고 토큰값과 API 서버 주소, 서비스 URL등을 .env 파일로 이관했습니다!
B. dev / production에 따라 env 파일을 다르게 로드할 수 있도록 세팅한 뒤, 자체 환경 변수에는 'NEXT' prefix 를 붙일 수 있도록 했습니다.
C. 추가로 Login / Register 페이지에서 쓰이던 loginNaver 함수를 제거하고, 앞으로 프론트에서 일어나는 SSO 관련 동작은 이곳에서 관리할 수 있도록 auth/openNaverSSO 로 분리했습니다.

2022-01-30 13:24 UTC, SolKimDev commented
env를 만들어두고 gitignore에 추가를 안해서 그냥 git에 올려버렸네요,,, 수정했습니다.. ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

2022-01-30 13:31 UTC, blurfx commented
제가 머지해서 컨플릭트가 났네요 😓  요것도 같이 수정 부탁드릴게요..!

2022-01-30 13:44 UTC, blurfx requested changes

2022-01-30 13:44 UTC, blurfx commented on next.config.js
> +  },
Next.js에서 기본적으로 .env를 통환 환경 변수 주입을 지원하고 있어서 따로 이렇게 작업하지 않아도 될 것 같습니다. 그래서 `dotenv` 패키지도 별도로 설치하거나 값을 관리할 필요가 없습니당

(https://nextjs.org/docs/basic-features/environment-variables)

2022-01-30 14:57 UTC, SolKimDev commented on next.config.js
> +  },
Next.js 빌트인 env를 활용할 수 있도록 수정하여 커밋했습니다!

2022-01-30 15:38 UTC, blurfx approved these changes
고생하셨습니다! 프로젝트 루트에 .env에 어떤 값들이 들어가는지 알수있게 키만 넣어놓은 `.env.example`같은 파일도 같이 넣어주시면 좋을 것 같아요!

```
NEXT_PUBLIC_URL=
NEXT_BACKEND_ADDR=
NEXT_PUBLIC_NAVER_TOKEN_CID=
```

2022-02-03 10:53 UTC, blurfx commented
merge conflict 해결해주시고 머지해주시면 될 것 같습니다!

2022-02-04 07:00 UTC, merged