프로젝트 전체조회 레이아웃 작성
DevCommunity-ko/Front pull request #16
Opened 2022-03-25 12:44 UTC by SolKimDev

프로젝트 전체 조회 레이아웃을 작성했고, 백엔드 API에 대한 상세한 명세가 없어 기능적 부분은 제외하고 구현했습니다.
세부사항은 다음과 같습니다
+ 요소 레이아웃 배치
+ 데이터가 연동되지 않은 상태의 프론트엔드 기능 ( 무한 스크롤 / 커스텀 드롭다운 필터 등 )
+ 접근성 개선 및 미사용 코드 삭제

작업 단위가 커서 그런지 커밋이 좀 많네요,, 😢

2022-04-07 15:05 UTC, blurfx reviewed
고생하셨습니다! 리뷰를 몇 개 달았으니 확인 부탁드려요.

2022-04-07 15:05 UTC, blurfx commented on src/components/common/Header.tsx
>      const pathnames = location.pathname.split('/');
원래 이 커밋에 포함되지 않는 부분은 건드리지 않는게 보통이지만… `location`을 직접 쓰기보다 `useRouter`를 사용하면 더 좋을 것 같아요. (죄송해요! 🙏)

2022-04-07 15:05 UTC, blurfx commented on src/components/common/Header.tsx
> +        break;
저희 로그인 페이지와 회원가입 페이지가 통합되었는데 이 로직이 필요한걸까요?

2022-04-07 15:05 UTC, blurfx commented on src/components/common/HiddenDescription.tsx
> +  clip: 'rect(0 0 0 0)',
스크린리더 - 접근성을 위해 `rect`나, `text-indent` 등으로 보이지 않는 레이블을 만드는건 대체로 안 좋은 선택입니다.

사용한 부분을 보니 `aria-label`과 같은 접근성 속성으로 처리가 가능할 것 같아요.

참고링크: https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-cues.html

2022-04-07 15:05 UTC, blurfx commented on src/components/project/DropdownMenuItem.tsx
> +      aria-checked={(isMultiple ? isSelected(item) : selectedValue?.value === item.value) ? 'true' : 'false'}
이 경우는 미리 표현식의 결과를 변수에 담아놓고 짧게 사용할 수 있을 것 같습니다.

2022-04-07 15:05 UTC, blurfx commented on src/components/project/FetchMore.tsx
> +  visibility: 'hidden',
`visibility`를 사용하신 이유가 궁금합니다!

2022-04-07 15:05 UTC, blurfx commented on src/hooks/useOutsideClick.ts
> +  const [target, setTarget] = useState<HTMLElement | null | undefined>(null);
`null`과 `undefined` 두 상태를 모두 허용해야하는 이유가 있을까요?

2022-04-07 15:05 UTC, blurfx commented on src/components/project/FilterDropdown.tsx
> +  placeholder?: string | undefined,
`placeholder?: string | undefined` 표현은 `undefined`를 두번 사용한 중복 표현입니다! 유니온 타입에서 제거하시면 좋을 것 같아요.

2022-04-07 15:05 UTC, blurfx commented on src/components/project/ProjItem.tsx
> +    return <></>;
tip: 아무것도 렌더링 하지않는 경우는 `React.Fragment`보다 `null`이 더 직관적입니다!

2022-04-07 15:05 UTC, blurfx commented on src/components/project/ProjItem.tsx
> +    <Wrapper role={'link'} tabIndex={0}>
링크처럼 동작하는 컴포넌트는 아닌것으로 보이는데 `role`을 `link`로 주신 이유가 궁금합니다.

2022-04-07 15:05 UTC, blurfx commented on src/components/project/ProjListContainer.tsx
> +        ((index % 4) === 0) && item && (<ProjListOneLine index={index} projListArray={list.list} key={index}/>)
`item`에 대한 검사는 필요없어 보입니다. 그리고 `0, 4, 8, 12, …`와 같이 0 또는 4의 배수인경우만 렌더링하는 것으로 보이는데 어떤 기능인가요?

2022-04-07 15:05 UTC, blurfx commented on src/components/project/SearchBox.tsx
> +      <StyledInput placeholder='입력하세요'/>
**나중에 같이 고민하면 좋을 부분 (그냥 읽고 넘어가주세요)**
`placeholder`는 `input`에 대한 예제 입력을 보여주는 용도로 사용하는 것이 best practice입니다. 나중에 어떤 값으로 대체할지 천천히 고민해봅시다!

2022-04-07 15:05 UTC, blurfx commented on src/components/project/SearchBox.tsx
> +  outline: 'none',
<kbd>Tab</kbd>키만으로 웹을 탐색하는 사람들을 위해, 웹 접근성 측면에서 `outline`을 없애더라도 포커스 되어 있을때 확실한 시각적 효과는 있으면 좋을 것 같습니다. 이 부분도 같이 천천히 고민해봅시다.

2022-04-07 15:05 UTC, blurfx commented on src/components/project/SearchBox.tsx
> +  border: '1px solid #E5E0EB',
색상들은 가능하면 `stitches.config.ts`에서 모두 관리되도록 해주세요!
이 부분 외에 몇 곳이 더 있습니다만, 하나씩 달면 너무 스팸같아 이 부분에만 달겠습니다

2022-04-07 15:05 UTC, blurfx commented on src/pages/index.tsx
> +const index = () => {
인덱스 페이지라 상관이 없긴하지만.. 컴포넌트의 이름은 대문자로 시작해야합니다!

2022-04-07 15:05 UTC, blurfx commented on src/pages/project/index.tsx
> +const Project = () => {
`ProjectPage`라는 이름이 더 직관적인 것 같습니다.

2022-04-07 23:43 UTC, SolKimDev commented on src/components/project/FetchMore.tsx
> +  visibility: 'hidden',
특별한 생각이 없었습니다.. 😢 
공간을 차지해야 할 이유가 전혀 없는데, display: 'none'이 아니라 visibility로 컨트롤 하는 이유가 뭔지 물어보신거죠..?
display를 이용하도록 수정해두겠습니다!

2022-04-08 07:10 UTC, SolKimDev commented on src/hooks/useOutsideClick.ts
> +  const [target, setTarget] = useState<HTMLElement | null | undefined>(null);
null로 수정하겠습니다!

2022-04-08 07:12 UTC, SolKimDev commented on src/components/project/FetchMore.tsx
> +  visibility: 'hidden',
수정 중 다시 확인해 봤는데, 지금처럼 IntersectionObserver를 이용하는 경우에 display:'none'을 적용하게 되면 인터섹션이 발생했다는 걸 감지하지 못하는 것 같아요,, 아무래도 이 부분은 visibility를 이용해야 하지 않을까 싶습니다 ㅠㅠ

2022-04-08 07:39 UTC, SolKimDev commented on src/components/project/ProjItem.tsx
> +    <Wrapper role={'link'} tabIndex={0}>
컴포넌트의 역할을 단순히 보았을 때 버튼을 눌러서 해당하는 프로젝트로 이동하는 링크로서 작동해야 하기 때문에, 스크린리더만을 가지고 웹의 구조를 파악하는 경우에는 링크로서 읽히는게 더 적합하지 않을까 생각해서 링크로 역할을 줘봤습니다!

2022-04-08 07:42 UTC, SolKimDev commented on src/components/project/ProjListContainer.tsx
> +        ((index % 4) === 0) && item && (<ProjListOneLine index={index} projListArray={list.list} key={index}/>)
ProjListOneLine에 전체 Array를 주고, 해당 컴포넌트에서 인덱스 기준 4개씩 한 줄로 출력하도록 만들어 두어서 index가 4배수일 경우에만 해당 컴포넌트가 렌더되도록 설계했습니다.
설계하면서도 뭔가 조금 어정쩡한 것 같다는 느낌이 들기는 했는데, 더 좋은 방법이 있을까요?

다른 페이지도 작성하다 보니 해당 로직이 되게 많이 반복되어서, 좀 더 정교하게 설계해서 패턴화시키는게 필요할 것 같긴 하더라구요.

2022-04-08 07:46 UTC, SolKimDev commented on src/components/project/SearchBox.tsx
> +  border: '1px solid #E5E0EB',
디자이너님이 Figma상에서 색상 아이템으로 지정해두지 않은 색상 코드는 위처럼 직접 색상 코드로 등록해서 사용했습니다.
코드상으로도 1~2회정도만 등장하는 색상이어서 그렇기도 했구요.
다만 #E5E0EB 색상같은 경우에는 여기저기서 많이 반복되는 것 같아 config.ts에서 관리할 수 있도록 하는게 맞을 것 같네요! 이 부분은 디자이너분께도 전달드리겠습니다.

2022-04-08 07:47 UTC, SolKimDev commented on src/components/project/SearchBox.tsx
> +  outline: 'none',
예은님께 포커싱 아웃라인 디자인 건의 드려볼게요!

2022-04-08 09:47 UTC, blurfx commented on src/components/project/FetchMore.tsx
> +  visibility: 'hidden',
좋아요!

2022-04-08 10:34 UTC, blurfx commented on src/components/project/DropdownMenuItem.tsx
> +      aria-checked={isSelectedExprResult ? 'true' : 'false'}
템플릿 리터럴 표현식이나 `.toString()` 메소드로 바로 원하는 값을 가져올 수 있을것 같아요

2022-04-08 10:34 UTC, blurfx commented on src/components/project/FilterDropdown.tsx
> +    selectedValues.map((item) => (str = str + item.label + ', '));
잘 작동 하는 코드지만, `map`을 올바른 용도로 사용하고 있지는 않습니다. 

아래 두 가지 방법중 하나를 추천드립니다.
1. `map`과 `join`을 사용하기
2. `reduce`를 사용하기

또, 선택한 아이템의 label이 각각 `A`, `B`, `C`일때 위의 코드로 실행을 시키면 `A,B,C,`가 되는데 의도하신 부분인지도 궁금합니다. (마지막 trailing comma가 들어가야하는 부분일까요?)

2022-04-08 10:34 UTC, blurfx commented on src/components/project/FilterDropdown.tsx
> +              (selectedValue ? selectedValue.label : item.placeholder)}
이 코드는 Nullish coalescing 연산자와 옵셔널 체이닝을 사용하면 조금 더 깔끔하게 만들 수 있을 것 같습니다.
(하지만 지금도 충분히 좋아요!)

2022-04-08 10:34 UTC, blurfx commented on src/components/project/FilterDropdown.tsx
> +                  item={dItem} key={dItem.value}
이렇게 사용할 때 한 줄에 여러개의 속성이 들어가는것은 피해주세요! 가독성이 낮아집니다.

2022-04-08 10:34 UTC, blurfx commented on src/components/project/DropdownMenuItem.tsx
> +  selectedValues: dropdownItem[],
`DropdownMenuItem`은 `isMultiple` 속성으로 여러개 선택 가능한지를 충분히 구분가능한 상태인데,
`selectedValue`와 `selectedValues`를 굳이 나눌 필요는 없어보입니다! 복잡도를 더 높이는 설계라고 생각해요.

2022-04-08 10:34 UTC, blurfx commented on src/components/project/ProjItem.tsx
> +    <Wrapper role={'link'} tabIndex={0}>
그렇군용. 다시 코드를 읽으면서 몇 가지 궁금증이 더 생겼습니다.

1. `Props`와 `ProjItemTypes`는 현재 구조상으로 분리되어있을 필요가 없어보인다는 생각을 했는데, 어떤 접근을 하신것인지 궁금합니다.
2. `[role="link"]`도 좋은 접근이지만, 링크로 동작하는 `a`대신 `div`를 사용하신 이유가 궁금합니다.
3. 지금은 `ProjItemTypes`의 모든 속성들을 사용하지 않고 있는데, 혹시 작업하다가 놓치신걸까요..!

2022-04-08 10:34 UTC, blurfx commented on src/components/project/ProjListContainer.tsx
> +        ((index % 4) === 0) && item && (<ProjListOneLine index={index} projListArray={list.list} key={index}/>)
아, 이해 했어요! 지금 화면에 그릴 스타일을 자바스크립트 단에서 처리하고 있는데 이대로 가면 반응형 레이아웃으로 작성할 때 문제가 될 것 같아요.

css `grid`를 사용하면 같은 레이아웃을 보여주면서 반응형도 얻어갈 수 있을 것 같은데 어떻게 생각하시나요?

2022-04-08 10:54 UTC, blurfx commented on src/components/project/FilterDropdown.tsx
> +          <MenuContainer onSubmit={(e) => onSubmit(e)}>
자식 요소(`DropdownMenuItem`)의 `role`의 `option`인 경우 `MenuContainer`의 `role`은 `listbox`가 되어야 할 것 같아요

2022-04-08 11:06 UTC, SolKimDev commented on src/components/project/ProjItem.tsx
> +    <Wrapper role={'link'} tabIndex={0}>
답변 드립니다! 
+ ![image](https://user-images.githubusercontent.com/29912273/162422235-815b60e0-653c-4965-af71-e91329f2b6c5.png) Props를 분리하지 않으면 해당 컴포넌트를 사용할 때 위와 같은 오류가 발생하더라구요. 오류를 해결하기 위한 선택이었습니다.
+ div로 우선 설계한 뒤 접근성을 개선시켰는데, 접근성 개선이 처음이다보니 기능을 적용할 생각만 했지 거기까진 생각이 못미쳤네요 ㅠㅠ 앵커로 수정한 뒤 커밋하겠습니다!
+ id,href,img는 백엔드 데이터가 없어 현재 프론트 설계 내에서 사용될 것 같은 데이터 포맷을 정의해뒀는데, 이 과정에서 미사용으로 남게 되었네요. 임의로 포맷을 정의한 뒤 사용하지 않고 두는 게 혹시 잘못된 접근 방법일까요?

2022-04-08 11:07 UTC, SolKimDev commented on src/components/project/ProjListContainer.tsx
> +        ((index % 4) === 0) && item && (<ProjListOneLine index={index} projListArray={list.list} key={index}/>)
반응형에 대해 일일히 대응해야 하나 고민하고 있었는데, 좋은 의견 감사드려요! 다음 커밋에 grid로 수정해서 반영해보겠습니다!

2022-04-08 11:09 UTC, blurfx commented on src/components/project/ProjItem.tsx
> +    <Wrapper role={'link'} tabIndex={0}>
잘못된 것은 아니지만 이해하기 어렵거나 영원히 사용되지 않는 코드로 남게 될 가능성이 높습니다.
어차피 서버에서 주는 데이터가 아직은 없으니 희수님이 생각하신 임의의 데이터가 온다고 가정하고, 필요한 값들을 모두 사용하면 더 좋을 것 같아요.

2022-04-08 12:29 UTC, SolKimDev commented on src/components/project/FilterDropdown.tsx
> +    selectedValues.map((item) => (str = str + item.label + ', '));
trailing comma같은 경우에는 윈도우 내레이터에서 이용해봤을때 comma 여부에 따라서 항목 사이 띄어 읽는 속도가 달라지더라구요. 사실 시각장애인분이 TTS 이용해 핸드폰 이용하는 UX 관련한 영상을 본 적 있는데, 지금 제가 설정해둔 속도보다 훨씬 빠르게 해서 들으시는데도 이용에 문제가 없으시다고는 하던데,, 아무래도 당사자가 아니다보니 어느 쪽이 사용성이 더 좋을지는 잘 모르겠긴 하네요,,ㅠㅠ

2022-04-09 14:23 UTC, blurfx commented on src/components/project/DropdownMenuItem.tsx
> +      return false;
👍  좋아요!
참고로 이렇게 배열에서 하나 이상의 요소가 조건을 만족하는지 확인하는 경우에는 `Array.some` 메소드를 사용하여 조금 더 단순화 시킬 수 있습니다.
```js
['a','b','c'].some((item) => item === 'a')
// true 
```

2022-04-09 14:23 UTC, blurfx commented on src/components/project/FilterDropdown.tsx
> +  const [selectedValue, setSelectedValue] = useState<dropdownItem | dropdownItem[] | undefined>(item.selectMultiple ? [] : undefined);
이렇게 `T | T[]`같은 타입을 자주 쓰게 된다면 나중에 `type SingleOrArray<T> = T | T[]` 같은 유틸리티 타입을 만들어서 사용해도 괜찮을 것 같아요.
지금은 안바꿔도 되는 상태라고 생각되어서 그냥 그렇구나 하고 넘어가주세용!

2022-04-09 14:23 UTC, blurfx commented on src/components/project/FilterDropdown.tsx
> +  const valuedIsArray = Array.isArray(selectedValue);
`valued` 오타인 것 같습니다 👀

2022-04-09 14:23 UTC, blurfx commented on src/components/project/DropdownMenuItem.tsx
> +      aria-checked={isSelectedExprResult}
👍 👍 👍

2022-04-09 14:30 UTC, SolKimDev commented on src/components/project/DropdownMenuItem.tsx
> +      return false;
결국 다 배열부분 기초군여,, ㅠㅠ
다음 푸시때 반영해볼게요!

2022-04-09 14:38 UTC, blurfx commented on src/components/project/DropdownMenuItem.tsx
> +      return false;
@SolKimDev 헉 맞다.. 제가 이 말을 빼먹었는데 요 부분도 꼭 바꿔달라고 코멘트 단 건 아니었습니다! (죄송해요 ㅠㅠ)

그 이유는 `map`, `reduce`, `filter`, `some` 같은 함수들은 함수 호출 오버헤드 때문에 함수가 불리는 횟수가 많아질수록 성능면에서 불리하기 때문인데요, 그래서 데이터가 많지 않은 경우에 코드의 가독성을 올리기 위해 쓰는게 좋습니다.

https://jsbench.me/ 에서 테스트한 스크린샷을 같이 올려드려요!

![스크린샷 2022-04-09 오후 11 35 19](https://user-images.githubusercontent.com/2173789/162578741-b99e0314-b0b3-40b2-bc76-b81d6e7abd26.png)

2022-04-09 14:42 UTC, SolKimDev commented on src/components/project/DropdownMenuItem.tsx
> +      return false;
앗,, 기본 라이브러리라고 무조건 깔끔하고 성능 좋을 거라고 생각하면 오산이군여,, ㅠㅠㅠ
알겠습니다,, 또 많이 배우네요,, ㅠㅠ
그치만 이번 같은 경우에는 어차피 필터 항목이라 나중에 세분화된다고 해도 두 자릿수를 넘지 않을 것 같으니, 적용해 보는 것도 좋을 것 같네요!

2022-04-15 08:17 UTC, SolKimDev commented
디자인 수정이 늦어지는 것 같아 1px outline만 적용하고 괜찮으면 바로 머지할게요!
외곽선 작업 관련해서는 수정사항 일어나면 별도 브랜치 파서 적용할까 합니다!

2022-04-23 14:43 UTC, blurfx requested changes
merge conflict도 이번에 같이 해결해주시면 좋을 것 같아요!

2022-04-23 14:43 UTC, blurfx commented on src/components/project/DropdownMenuItem.tsx
>        }
이 부분에서 이제 `for`문이 없어도 될 것 같아요!

원래 `for.. + if`로 하던 것을 `Array.some`으로 처리하니까요!

2022-04-24 12:30 UTC, blurfx approved these changes
고생하셨어요!!

2022-04-24 12:31 UTC, merged