Sol
DevCommunity-ko/Front pull request #2
Opened 2021-12-25 10:21 UTC by SolKimDev

PR 수행
Register 및 Login페이지 작업됨
헤더 스태시 내용 머지하였음
상세정보 입력 / 전문분야 설정 페이지에 대한 수정사항은 아직 반영되지 않음

2021-12-25 11:37 UTC, blurfx reviewed
리뷰 남깁니다!

2021-12-25 11:37 UTC, blurfx commented on components/auth/TextInputBox.tsx
> +        />
`input`에 대한 설명 텍스트로는 `p` 대신 `label`을 쓰는 것이 웹 접근성 측면에서 더 좋을 것 같습니다.

2021-12-25 11:37 UTC, blurfx commented on components/auth/TextInputBox.tsx
> +  }
`input`에 대한 스타일이 부모 요소의 스타일에 정의되어 있는데, `input`에 대한 스타일을 분리하는게 더 깔끔할 것 같습니다.
`styled-component`나 그와 비슷한 css-in-js 라이브러리를 사용하며 얻는 이점이 스타일을 선언적으로 + 컴포넌트별로 분리해 관리를 할 수 있다는 점이니 그에 맞게 쓰면 좋을 것 같아요!

2021-12-25 11:37 UTC, blurfx commented on components/auth/TextInputBox.tsx
> +  }
`ButtonArea` 내에 있는 `label` 역시 별도의 styled component로 분리하면 좋을 것 같아요!

2021-12-25 11:37 UTC, blurfx commented on components/common/Header.tsx
> +`;
요건 다른 이야기인데, 메뉴에 마우스를 올렸을 때 마우스가 올라가지 않은 다른 메뉴의 색이 바뀌는게 되게 부자연스러운 것 같아요.
내가 마우스를 올린 메뉴의 색이 바뀌는 것을 보통 기대하는데, 오히려 올라가지 않은 애들의 색이 바뀌어버리니까 사용자 입장에서 뭔가 문제가 있는 느낌이 강하게 듭니다. -> UX가 이상해요
디자이너분이랑 한번 이야기를 하면 좋을 것 같아요!

2021-12-25 11:37 UTC, blurfx commented on components/auth/TextInputBox.tsx
> +};
상당히 많은 부분이 input의 속성에 들어가는 값으로 보이는데, 이 경우에는 `React.HTMLProps` 타입을 사용해서 원하는 HTML 엘리먼트의 속성들을 타입으로 가져와 확장해서 쓰면 더 편할거 같아요.

```typescript
type TextInputProps = React.HTMLProps<HTMLInputElement> & {
  label: string;
  errorMsg?: string;
  …
}
```

2021-12-25 11:37 UTC, blurfx commented on containers/auth/RegisterForm.tsx
> +      <p>careerLength : {registerForm.careerLength}</p> */}
이런 디버그용 코드들(`console.log` 도요)은 push 전에 삭제해주는 것이 좋습니다!

2021-12-25 11:37 UTC, blurfx commented on components/auth/CheckboxItem.tsx
> +      ) : (
특정 조건이 참일때만 렌더링하고, 거짓일때는 아무것도 렌더링하지 않는다면 삼항연산자보다 AND 연산이 더 직관적일것 같습니다.

`{ condition && <MyComponent>…</MyComponent }`

2021-12-25 11:37 UTC, blurfx commented on components/auth/RegisterAgreement.tsx
> +  const [checkedList, setCheckedLists] = useState([
전체 동의와 각 개별 동의 문항이 하나의 State로 관리되고 있는데, 전체 동의는 각 개별 문항의 상태를 반영하는 부분이라 별개로 분리하는게 좋을 것 같습니다.

2021-12-25 11:37 UTC, blurfx commented on components/auth/RegisterAgreement.tsx
> +      arrayCopied[1] && arrayCopied[2] && arrayCopied[3] && arrayCopied[4];
지금은 몇 개 되지 않아서 괜찮지만, 하나씩 평가하기보다 JavaScript의 `Array.every` 함수를 쓰면 조금 더 깔끔하게 바꿀 수 있을 것 같습니다.

```typescript
const allChecked = arrayCopied.every(Boolean);

// Example
[true, true, true, true].every(Boolean) // => true
[true, true, true, false].every(Boolean) // => true

[3, 1, 2, 9].every((val) => val > 1) // => false
[3, 2, 2, 9].every((val) => val > 1) // => true
```

2021-12-25 11:37 UTC, blurfx commented on components/auth/RegisterAgreement.tsx
> +        agreements: [ checkedList[1], checkedList[2], checkedList[3], checkedList[4]]
slice를 사용해서 1번째 인덱스 요소부터 잘라낼 수 있겠지만.. 위에서 말씀드린대로 State를 분리한다면 더 깔끔하게 처리가 될 것 같네용 👀

2021-12-25 11:37 UTC, blurfx commented on components/auth/RegisterAgreement.tsx
> +      <FormBlock id="AgreeForm" isShowAll={isShowAll ? 1 : 0}>
1과 0만으로 상태를 나타내는데 지금 `number`로 받고 있어서 `bool ? 1 : 0`형태로 쓰시는 것 같습니다. `number`보다 `boolean`을 받고, 단순히 `isShowAll`을 그대로 넘겨주면 어떨까요?

2021-12-25 11:37 UTC, blurfx commented on components/auth/RegisterAgreement.tsx
> +          isErrorShown={isErrorShown ? 1 : 0}
여기 있는 `isShowAll`, `isErrorShown`도 위와 같이 `number`대신 `boolean` 타입으로 값을 받는게 더 나을 것 같습니다.

2021-12-25 11:37 UTC, blurfx commented on components/auth/RegisterDetail.tsx
> +  ]);
모든 필드를 하나의 State로 관리하는 것보다 별개의 State로 관리하는게 더 직관적이고 깔끔합니다. `react-hook-form` 같은걸 도입해서 깔끔하게 폼 필드 관리를 해보는 것은 어떨까요??

2021-12-25 11:37 UTC, blurfx commented on components/auth/RegisterDetail.tsx
> +  const verifyAllFields = () => {
폼 검증 로직은 중요하지만.. 조금 더 단순화 할 필요가 있는 것 같습니다. `zod`같은 schema validation 라이브러리를 사용해보시는건 어떨까요?

2021-12-25 11:37 UTC, blurfx commented on components/auth/RegisterDetail.tsx
> +    }
이런 경우는 오히려 `isErrorFound`가 참인지 검사하고 참이라면 함수를 바로 나가버리도록 하는게 더 나을 것 같습니다. 이렇게 하면 실제로 동작하는 코드들이 1-depth 위로 올라옵니다.

2021-12-25 11:37 UTC, blurfx commented on components/auth/RegisterField.tsx
> +  ]);
이 경우에는 하나의 컴포넌트로 모든 State를 내려주는 방식이라 어쩔 수 없지만, 배열 대신 딕셔너리를 사용하는 것이 더 확장성 있고 직관적일 것 같습니다. `fieldDataList[0]` 보다는 `fieldData.workfield`가 더 직관적이니까요.

2021-12-25 11:37 UTC, blurfx commented on components/auth/TextInputBox.tsx
> +          placeholder={errorStatus ? errorMsg : placeholder}
오류 메시지는 `placeholder`에 넣으면 안됩니다! 왜냐하면:
1. 이 인풋에 어떤 값이 들어가야하는지에 대한 예제를 넣는 속성이에요.
2. 사용자가 값을 입력하지 않았을때만 동작합니다. 이상한 값을 넣어 오류가 발생한 경우(전화번호 필드에 한글이 들어가있다던가..)에는 동작하지 않습니다.

2021-12-25 11:37 UTC, blurfx commented on components/auth/TextInputBox.tsx
> +        ChangedList[5] = 'error';
`switch case`도 좋은 해결책이지만, 각 케이스에서 하는 액션이 모두 `ChangeList[5]를 수정한다`로 같은 것 같습니다. 이런 경우에는 딕셔너리를 쓰는게 어떨까요?

```typescript
const gener = {
  gender_0: 'male',
  gender_1: 'female',
  gender_2: 'else',
}

ChangeList[5] = gender[e.target.id] ?? 'error'
```

2021-12-25 11:37 UTC, blurfx commented on components/auth/TextInputBox.tsx
> +    switch (e.target.id) {
값을 가져오는데 `id`는 별로 좋지 않은 선택같습니다. `value`에 `male`, `female`, `else`를 주고 이 값을 사용하면 어떨까요?

2021-12-25 11:37 UTC, blurfx commented on store/modules/loading.ts
> +      action.payload.false;
제가 Redux와 RTK에 익숙하지 않아서 질문드립니다. 이 부분은 오타일까요? 위의 코드를 보면 `action.payload = false`가 맞는것 같아서요..!

2021-12-25 11:37 UTC, blurfx commented on store/modules/auth.ts
> +  error: any;
`any`는 가능하면 피해주세요! 어떤 타입이 들어올지 알 수 없어서 `any`를 사용하신거라면 `unknown`이나 제네릭 타입이 더 맞습니다.

2021-12-25 11:39 UTC, blurfx commented
그리고 PR에 올라온 변경사항과 별개로 `tsconfig.json`에 `strict` 옵션이 꺼져있더라구요.. next의 기본 설정인지, 아니면 초기에 작업하신분이 끄신 것인지는 모르겠는데 `strict`를 끄면 TS를 쓰는 이유가 없다고 생각을 해서.. 키고 진행하는걸 추천드립니다..!

2021-12-28 13:04 UTC, SolKimDev commented on store/modules/auth.ts
> +  error: any;
네 알겠습니다~!

2021-12-28 13:38 UTC, SolKimDev commented on components/auth/TextInputBox.tsx
> +          placeholder={errorStatus ? errorMsg : placeholder}
디자이너분께 전달사항 남겼습니다!

2021-12-28 15:16 UTC, SolKimDev commented on components/auth/RegisterField.tsx
> +  ]);
DetailPage 삭제 후 State 재구성하며 해결해 보겠습니다!

2021-12-28 18:09 UTC, blurfx requested changes
리뷰 남깁니다! 흑흑 이번에도 제가 뭐라 많이 써놨는데 무서워하지 말아주세요 (혹시나 해서.. 🥺)

2021-12-28 18:09 UTC, blurfx commented on components/auth/AuthTemplate.tsx
> +export const AuthTemplate = ({ children }: AuthTemplateBlockProps) => {
`React.PropsWithChildren`이나 `React.FC`같은 타입을 사용해주시면  `children`을 매번 타입에 넣어주지 않으셔도 됩니다.

**React.PropsWithChildren**
```typescript
export const AuthTemplate = ({ children }: React.PropsWithChildren<unknown>) => {
  return <AuthTemplateBlock>{children}</AuthTemplateBlock>;
};
```
**React.FC**
```typescript
export const AuthTemplate: React.FC = ({ children }) => {
  return <AuthTemplateBlock>{children}</AuthTemplateBlock>;
};
```

지금은 `children`만 필요한 상황이지만 커스텀한 Props를 받아야 한다면 아래와 같이 쓸 수 있습니다!

```typescript
interface Props {
  label: string;
  value: string;
};

export const MyComponent: React.FC<Props> = ({ children, label, value }) => { … };
```

```typescript
type Props = React.PropsWithChildren<{
  label: string;
  value: string;
}>;

export const MyComponent = ({ children, label, value }: Props) => { … };
```

2021-12-28 18:09 UTC, blurfx commented on components/auth/CheckboxItem.tsx
> +  onCheck: React.ChangeEventHandler<HTMLInputElement>;
`onCheck`는 '체크 되었을 때만 트리거되는' 이벤트 같은 느낌을 줍니다. `onUnchecked`도 있을 것 같은 생각이 드는 이름이라 생각합니다. 원래 이벤트 핸들러 이름 그대로 `onChange`라 해도 좋을 것 같아요!

2021-12-28 18:09 UTC, blurfx commented on components/auth/CheckboxItem.tsx
> +  showAll?: React.MouseEventHandler<HTMLSpanElement>;
`showAll`은 실제로 함수지만, 이름만 보면 어떤 상태를 나타내는 것처럼 보여요. 또 `formItem.showAll`과 이름이 같기도 해서 코드를 보면서 이게 `formItem.showAll`인지 아니면 그냥 `showAll`인지 헷갈리게 만드는 것 같습니다.
더 좋은 이름으로 바꿔보면 어떨까요? `onClickShowMore` 를 조심스레 추천드려봅니다.

2021-12-28 18:09 UTC, blurfx commented on components/auth/CheckboxItem.tsx
> +            isTitle={formItem.showAll ? true : false}
`formItem.showAll`이 이제 `boolean` 타입이니 삼항 연산자를 없애도 될 것 같아요. 지금의 코드는 `isTitle={formItem.showAll}` 와 완전히 같습니다!

2021-12-28 18:09 UTC, blurfx commented on components/auth/CheckboxItem.tsx
> +  isRequired: boolean;
`isRequired` 대신 그냥 `input` 요소가 사용하는 `required`를 같이 사용하면 어떨까요? 아마 이게 같이 사용이 되나 싶어서 분리해서 사용하신걸로 생각됩니다. 둘이 같이 사용할 수 있어요!

2021-12-28 18:09 UTC, blurfx commented on components/auth/CheckboxItem.tsx
> +      {formItem.subHead ? <SubHeadBlock>{formItem.subHead}</SubHeadBlock> : ''}
여기도 `{formItem.subHead && …}`과 같은 방식으로 바꿔주시면 좋을 것 같아요!

2021-12-28 18:09 UTC, blurfx commented on components/auth/CheckboxItem.tsx
> +      }
혹시 transition 을 고려하고 이렇게 해주신걸까요? 만약 아니라면, `display: none;`으로 같은 동작을 만들 수 있을것 같습니다.

2021-12-28 18:09 UTC, blurfx commented on containers/auth/RegisterForm.tsx
> +  const [registerForm, setRegisterForm] = useState({
이렇게 복잡한 값을 `useState`로 다루는 경우에 타입을 명시해주면 좋습니다. 
```typescript
import type { RegisterPayload } from '../../store/modules/auth';

useState<RegisterPayload>({ … })
```;

2021-12-28 18:09 UTC, blurfx commented on components/auth/RegisterAgreement.tsx
> +  registerForm: object;
`object`보다는 `Record<T, U>`타입을 사용하는게 좋지만, 이 경우에는 `Record` 타입보다 `RegisterPayload`라는 저희가 미리 정의한 타입이 있으니 그 타입을 쓰면 좋을 것 같아요.

2021-12-28 18:09 UTC, blurfx commented on components/auth/RegisterAgreement.tsx
> +    ]);
이렇게 바꿔보면 어떨까요? 더 깔끔하고, State의 길이가 늘어나는 경우에 유연하게 대처할 수 있을것 같습니다.
```suggestion
    setCheckedLists((prev) => prev.map(!isCheckedAll));
```

2021-12-28 18:09 UTC, blurfx commented on components/auth/RegisterAgreement.tsx
> +    let arrayCopied = [...checkedList];
큰 변화는 없을테지만, 이 변수는 `const`로 선언해도 무방합니다.

2021-12-28 18:09 UTC, blurfx commented on components/auth/RegisterAgreement.tsx
> +  const onButtonClick = (e: { preventDefault: () => void; }) => {
이벤트 핸들러 타입을 잡아주시면 좋을 것 같아요!

2021-12-28 18:09 UTC, blurfx commented on components/auth/RegisterAgreement.tsx
> +    }
이런 경우에는 early-return 을 하면 주로 실행되는 코드의 깊이를 얕게 만들 수 있습니다. 
```suggestion
    if (!(checkedList[0] && checkedList[1])) {
      setIsErrorShown(true);
      return;
    }

    const agreementsAdded = {
      ...registerForm,
      agreements: checkedList,
    };
    setRegisterForm(agreementsAdded);
    toPageNext();
```

2021-12-28 18:09 UTC, blurfx commented on components/auth/RegisterAgreement.tsx
> +  color: transparent;
지금 `isErrorShown`이 `false`일때는 투명색을 사용하여 안보이게 해주셨는데, 항상 붉은색 글씨를 사용하는 대신에 `isErrorShown`이 참일때만 이 컴포넌트가 렌더링되게 하면 어떨까요? 다른 곳에서 해주셨던 것처럼요!

`{ isErrorShown && … }`

2021-12-28 18:09 UTC, blurfx commented on components/auth/TextInputBox.tsx
> +          {buttonText ? <TextButton>{buttonText}</TextButton> : ''}
이 친구도 `{ buttonText && … }`같이 바꿔주시면 좋을 것 같아요

2021-12-28 18:09 UTC, blurfx commented on components/auth/TextInputBox.tsx
> +          {buttonList
`buttonList`도 `{ buttonList && … }`처럼 바꿀 수 있어보입니당

2021-12-28 18:09 UTC, blurfx commented on components/auth/TextInputBox.tsx
> +        {dropdown ? (
dropdown도요! `{ dropdown && … }`로 바꾸면 좋을 것 같아요

2021-12-28 18:09 UTC, blurfx commented on components/common/Responsive.tsx
> +interface ResponsiveProps {
여기도 `AuthTemplate`에서 말씀드렸던 것을 참고해보시면 좋을 것 같아요!

2021-12-28 18:09 UTC, blurfx commented on containers/auth/RegisterForm.tsx
> +  return (
이 페이지에 있는 친구들도 `{ condition ? ReactNode : '' }`꼴 대신 `{ condition && ReactNode }`로 바꾸면 좋을 것 같아요

2021-12-28 18:14 UTC, blurfx commented on components/auth/RegisterDetail.tsx
> +  const onButtonClick = async (e: React.MouseEvent<HTMLSpanElement, MouseEvent>) => {
`React.MouseEvent`에서 두번째로 오는 이벤트의 타입 같은 경우 기본값으로 `MouseEvent`라 안 넣어주셔도 됩니당.

`React.MouseEvent<HTMLSpanElement>`로 조금 더 짧게 쓸 수 있어요!

2021-12-28 18:15 UTC, blurfx commented on components/auth/RegisterField.tsx
> +  const onClick = (e: React.MouseEvent<HTMLSpanElement, MouseEvent>) => {
여기도 `React.MouseEvent<HTMLSpanElement>`로 짧게 바꿔볼 수 있을 것 같아요

2021-12-29 01:21 UTC, SolKimDev commented on components/auth/CheckboxItem.tsx
> +            isTitle={formItem.showAll ? true : false}
현재 text.ts 파일에서 showAll: true | undefined로 정의가 되어 있어서요.
그래서 {formItem.showAll}만 사용했을 경우 정의된 오버로드가 없다고 에러가 뜨는데, 이런 경우에는 text.ts 쪽을 수정하는게 나을까요?

2021-12-29 01:51 UTC, SolKimDev commented on components/auth/RegisterField.tsx
> +  ]);
해결하려다보니 TextInputBox 컴포넌트에서 DataList를 받는 형식까지 바꿔야만 해결될 문제 같아 보여서요.. 이 부분에 대해서는 현상 유지를 하는 건 어떨까요?

2021-12-29 05:22 UTC, blurfx commented on components/auth/CheckboxItem.tsx
> +            isTitle={formItem.showAll ? true : false}
`showAll`이 `undefined`인 경우에는 어떤 경우를 나타내는건가요?

2021-12-29 05:39 UTC, SolKimDev commented on components/auth/CheckboxItem.tsx
> +            isTitle={formItem.showAll ? true : false}
기본값으로 false를 사용하는게 의미가 더 명확하게 할 수 있는 상황이라고는 생각해요!
showAll=true인 경우에만 정의해주고, 이외의 경우 falsy한 값을 false로 간주해 사용할 수 힜겠다고 생각했고, ts strict가 꺼져 있던 상태여서 정의하지 않고 간편하게 사용할 수 았겠다 싶은 생각에 이렇게 정의했을 뿐이에요!

2021-12-29 05:58 UTC, blurfx commented on components/auth/CheckboxItem.tsx
>          )}
앗 여기도… 부탁드려요!

2021-12-30 06:07 UTC, blurfx commented on components/auth/RegisterField.tsx
> +  ]);
헉 이걸 지금 봤네요 ㅠㅠ TextInputBox가 동작에 비해 너무 많은 컨텍스트를 가지고 있어서 많이 까다롭긴 할 것 같아요. 혹시 괜찮으시다면, 페어 프로그래밍을 해보는건 어떨까요?

2021-12-30 06:13 UTC, blurfx commented on components/auth/RegisterField.tsx
> +  ]);
우선은 단순하게 아래의 두 컴포넌트로 분리해보면 좋을 것 같아요!

- input만 있는 `컴포넌트 A`
- `컴포넌트 A`와 button이 같이 있는 컴포넌트

2021-12-30 07:45 UTC, blurfx approved these changes
코드가 많이 좋아졌네요! 고생하셨어요 👍
`TextInputBox`는 조금 더 리팩토링하면 좋을 것 같은데 이 PR은 먼저 머지를 하고 따로 얘기를 해보면 어떨까요?

2021-12-30 07:55 UTC, SolKimDev commented on components/auth/RegisterField.tsx
> +  ]);
우선 분리해봤습니다! 그치만 DataList State의 구조와 InputBox 컴포넌트에서 이걸 받아들이는 방법 모두를 변경해야 할 것 같은데, 아직은 잘 모르겠네요,, ㅠㅠ

2021-12-30 08:29 UTC, merged