Magnet 77
DevCommunity-ko/Front pull request #9
Opened 2022-01-11 15:14 UTC by SolKimDev

아직 디자인이 나오지 않은 (max-width 360)을 제외한 모든 반응형 디자인을 헤더와 로그인/회원가입 페이지에 반영하였습니다.

커밋 `348fb48` 의 이전 커밋까지는 반응형 디자인이 확정되지 않아 내용이 계속 수정된 부분이 많으니 리뷰하실 때 참고 부탁드릴게요!

2022-01-13 17:14 UTC, blurfx requested changes
리뷰 남겼습니다!

2022-01-13 17:14 UTC, blurfx commented on src/components/auth/RegisterAgreement.tsx
> +  const screenChange = (event: { matches: boolean }) => {
`event: { matches: boolean }`같이 타입을 직접 정의하는 것보다 미리 정의된 타입을 사용하는게 더 직관적입니다. 이 경우에는 `MediaQueryListEvent`를 사용하면 될것 같아요.

2022-01-13 17:14 UTC, blurfx commented on src/components/auth/RegisterAgreement.tsx
> +    const matches: boolean = event.matches;
가져올 객체 필드의 이름과 할당할 변수의 이름이 같은 경우에는 객체 분해 문법을 사용하면 더 깔끔하고 가독성이 좋습니다.

```suggestion
    const { matches } = event;
```

ref: https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

2022-01-13 17:14 UTC, blurfx commented on src/components/auth/RegisterAgreement.tsx
> +    const mql = window.matchMedia('screen and (max-width: 640px)');
변수에 담기지 않고 코드에서 맥락없이 나오는 값을 보통 매직 넘버라고 하는데, 많은 경우에 다른 개발자들에게 이 값이 어떤 의미로 사용되는지 전달이 잘 안됩니다. 그래서 가능하면 `const mobileScreenWidth = 640;`과 같이 충분한 의미를 내포하는 변수를 만들고 이 변수를 사용하는 것이 좋습니다.

2022-01-13 17:14 UTC, blurfx commented on src/components/auth/RegisterAgreement.tsx
> +  // api/auth쪽으로 분리하는게 나을까요??
`api/auth`쪽도 좋을 것 같아요. 하지만 직접 api를 호출하는건 아니기에 추후에 redux 로그인 관련 slice action으로 빼면 더 깔끔할 것 같습니다.

당장은 굳이 안 빼도 될것같으니 TODO 주석 하나만 달아주시면 좋을 것 같아요. 🤗

2022-01-13 17:14 UTC, blurfx commented on src/components/auth/RegisterAgreement.tsx
> +  borderRadius: '50px',
px대신 rem을 사용하는 것을 권장합니다!
아마 저번에 같은 내용으로 한번 말씀드린 것 같아서 이번에는 설명을 안드려도 될 것 같아요..! 혹시 제가 설명을 안했다면 말씀해주세요!

2022-01-13 17:14 UTC, blurfx commented on src/components/common/Header.tsx
> +  const user = '수민'; // Redux 작업 하시면서 변경 부탁드릴게요!
🙆‍♂️

2022-01-13 17:14 UTC, blurfx commented on src/components/common/Header.tsx
> +    const lastPath = regGetLastPath.test(window.location.href) && RegExp.$1;
url에서 마지막 path를 가져오시려고 한것 같아요! 이 경우에 `href` 대신 `pathname`을 쓰면 조금 더 깔끔해집니다.



```javascript
// 현재 url이 https://github.com/DevCommunity-ko/Front/pull/9/files#diff 일때

location.pathname
>> '/DevCommunity-ko/Front/pull/9/files'

// '/'를 기준으로 문자열을 나누고 마지막 원소만 남깁니다.
location.pathname.split('/').slice(-1)
>> ['files']

// 인덱스에 접근하여 바로 가져올 수 있습니다.
location.pathname.split('/').slice(-1)[0]
>> 'files'

// 하지만 현재 url이 https://github.com/DevCommunity-ko/Front/pull/9/files/#diff 일때는 좀 다릅니다.
// (files 뒤에 / trailing slash가 붙었습니다)

location.pathname
>> '/DevCommunity-ko/Front/pull/9/files/'

// trailing slash 때문에 빈 문자열이 추가되었습니다.
const pathnames = location.pathname.split('/');
>> ['', 'DevCommunity-ko', 'Front', 'pull', '9', 'files', '']

// 빈 문자열은 falsy하다는 것을 이용해 아래와 같이 logical OR로 처리할 수 있습니다.
const lastSegment = pathnames.pop() || pathnames.pop();
>> 'files'

```

2022-01-13 17:14 UTC, blurfx commented on src/components/common/Header.tsx
> +              {/* 게시판 리스트 현재 확정되지 않고 변동 가능성 있어 하드코딩 해 두었습니다. */}
🙆‍♂️

2022-01-13 17:14 UTC, blurfx commented on src/containers/auth/LoginForm.tsx
> +    const matches: boolean = event.matches;
이 부분도 객체 분해 문법을 사용하면 더 깔끔해질 것 같습니다 :)

2022-01-13 17:14 UTC, blurfx commented on src/containers/auth/LoginForm.tsx
> +    const mql = window.matchMedia('screen and (max-width: 640px)');
매직 넘버 역시 앞서 말한대로 수정이 가능할 것 같아요.

2022-01-13 17:18 UTC, blurfx commented
중복되는 댓글이 너무 많을것 같아 따로 남깁니다.

1. 전체적으로 css 상에서 `rem`유닛을 쓰고 있는데 이 부분들은 polished 라이브러리의 rem 함수로 대체하면 확실히 어떤 값인지 읽기 쉬울 것 같습니다.

2. stitches에서 컬러 토큰을 관리하니, 이제 스타일에 직접 색상값을 넣으면 색상 토큰 관리 측면에서 파편화가 일어납니다. 이 PR 두세군데에서 색상값을 스타일에 직접 넣어 사용하고 있는데, stitches colors 토큰을 사용해주시면 나중에 색상값 추적이 훨씬 쉬울 것 같습니다!
  (비슷한 색상을 가진 토큰을 사용하셔도 좋고, 혹은 그냥 새 색상 토큰을 만들어서 사용하셔도 좋습니다.)

2022-01-19 12:00 UTC, SolKimDev commented on src/components/auth/RegisterAgreement.tsx
> +  const screenChange = (event: { matches: boolean }) => {
적용은 했습니다만, TS가 처음이다보니 자꾸 이런 부분에서 지적을 듣게 되네요,, ㅠㅠ
그래서 이런 부분들에 대해서 공부해 보고 싶은데, 혹시 어떤 키워드로 찾으면 좋을지 여쭤봐도 괜찮을까요??

2022-01-19 12:05 UTC, SolKimDev commented on src/components/auth/RegisterAgreement.tsx
> +  borderRadius: '50px',
이 부분은 개인적으로 나중에 리소스를 받고 대체될 요소들의 경우 임시로 px단위를 적용해 두었는데, 아무래도 rem 단위를 적용하고, 주석 등으로 명시적으로 리소스로 교체될 요소임을 표현하는 게 낫겠죠...?

2022-01-19 12:11 UTC, SolKimDev commented
1. 다음 커밋에서 일괄적으로 하드코딩된 rem 단위를 polished 라이브러리로 대체하는 작업을 진행하겠습니다!
2. 아마 컬러 토큰이나, 앞서 나온 px 단위 같은 경우들은 언급했던 임시 요소들에 한해 적용해 둔 부분들로 기억하는데, 이런 임시 요소들 같은 경우에도 일괄적으로 표준화시켜 진행하는 게 나을까요?
2-1. 그리고 색상 또한 임시로 디자인 된 버튼이라고 생각해서, 버튼 리소스를 받고 나면 지금 지정했던 색이나, 버튼에 대해 지정된 스타일 들은 전부 사용되지 않고 사라질 값이 (임시로 한정해 1회만 사용되고, 추후 수정되며 사라질 색상 코드)라고 생각해서 하드코딩 해 두었는데, 앞으로 이런 부분이 또 발생할 경우 어떻게 처리하면 좋을지에 대해서도 이야기 나눠 보고 싶네요!

2022-01-19 13:24 UTC, blurfx commented on src/components/auth/RegisterAgreement.tsx
> +  const screenChange = (event: { matches: boolean }) => {
DOM과 관련된 대부분의 이벤트는 이미 내부적으로 정의되어 있어서 마우스 커서를 올리거나 혹은 Cmd+클릭(아마 윈도우는 Ctrl + 클릭..?)으로 내부 구현을 보면 대부분의 타입 정의를 찾아볼 수 있습니다. 그 외에도 Nextjs나 Gatsbyjs같은 프레임워크들을 쓸 때도 대부분은 이미 내부에 타입이 정의되어 있기에 잘 살펴보면 찾을 수 있어요.

혹은 이런 경우처럼 `media query onchange event` 같은 식으로 검색을 하고, MDN 같은 문서를 찾아보면 https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/onchange 어떤 이벤트를 받고 있는지 나와 있습니다. 리액트에 똑같은 이름으로 타입이 정의되어 있는 경우가 많으니 문서만 보고 리액트에서 비슷한 이름의 타입을 찾아봐도 좋을 것 같아요.

![스크린샷 2022-01-19 오후 9 53 11](https://user-images.githubusercontent.com/2173789/150134485-b1b6c0f2-1708-4c02-abe0-a105b17e08a8.png)

2022-01-19 13:26 UTC, blurfx commented
헉 임시적인 요소라면 상관 없을거 같아요. (혹시 전에 말씀해주셨는데 제가 기억을 못하는거라면 죄송합니다 😭 )
대신에 `// FIXME: 임시 색상 제거하기` 같은 식으로 주석을 남겨놓으면 좋을것 같아요.

2022-01-19 13:50 UTC, SolKimDev commented on src/components/auth/RegisterAgreement.tsx
> +  const screenChange = (event: { matches: boolean }) => {
그때그때 case by case로 알아보며 익숙해지는 것이 최선이란 말씀이시군요,, 알겠습니다! 감사해요!

2022-01-19 13:52 UTC, SolKimDev commented
아니에요 제가 명확히 하거나 전달해드렸어야 했는데 깜빡했네요 ㅠㅠ
나머지 반영해서 request 드릴게요!

2022-01-22 05:37 UTC, SolKimDev commented
대부분의 하드코딩된 rem 단위를 rem( ) 함수를 이용하도록 수정했습니다.
더불어 이전 PR 요청때 작성되지 않았던 360 해상도의 반응형 디자인이 작성되어 있어, 해당 부분 반영함과 동시에
640 해상도에서 적용되야 하는 디자인 수정 사항도 적용했습니다.

2022-01-22 14:09 UTC, blurfx requested changes
리뷰 남겼습니다!

2022-01-22 14:09 UTC, blurfx commented on src/containers/auth/LoginForm.tsx
어차피 임시용 컴포넌트라 별 상관은 없지만 그냥 적어보자면 완벽한 원형을 원하는 경우는 그냥 border-radius를 100%로 주면 됩니다.

2022-01-22 14:09 UTC, blurfx commented on src/containers/auth/LoginForm.tsx
> +    const mql = window.matchMedia('screen and (max-width: 640px)');
```suggestion
    const mql = window.matchMedia(`screen and (max-width: ${mobileWidthLarge}px)`);
```
미디어 쿼리 테스트에 사용할 너비값도 앞에서 선언했던 변수를 사용하면 어떨까요?

2022-01-22 14:09 UTC, blurfx commented on src/containers/auth/LoginForm.tsx
> +    const mobileWidthLarge = 640; // @mobileLarge
```suggestion
    const mobileLargeWidth = 640; // @mobileLarge
```

`mobileLarge`의 `width`이라는 뜻으로 이렇게 바꾸면 조금 더 자연스러워 보일 것 같습니다.

2022-01-22 14:09 UTC, blurfx commented on src/components/common/Header.tsx
> +  const user = '수민'; // Redux 작업 하시면서 변경 부탁드릴게요!
여기 주석도 `// TODO: …` 형태로 바꿔주시면 나중에 변경할 때 찾기 좋을 것 같아요.

2022-01-22 14:09 UTC, blurfx commented on src/components/common/Header.tsx
> +       여기에 Redux와 연동된 setIsLoggedIn() 구문이 필요합니다.
여기도…?! `/* … TODO: … … */`

2022-01-22 14:13 UTC, blurfx commented on src/components/auth/AuthTemplate.tsx
> +    marginTop: rem(110), // 190 - 80(Header Height);
이번 PR 스코프는 아니지만, 일단 남겨봅니다. 논의 후에 변경이 필요하다면 다른 PR로 넘어가면 좋을 것 같아요

marginTop이 데스크탑 환경에서도 과하게 잡혀있는 느낌입니다. `flexbox`같은 것을 사용해서 가운데 정렬을 하는게 오히려 더 깔끔할 것 같은데 그러지 않은 이유가 있을까요?

2022-01-23 11:25 UTC, SolKimDev commented on src/components/auth/AuthTemplate.tsx
> +    marginTop: rem(110), // 190 - 80(Header Height);
처음에 레이아웃을 잡을 때, 피그마 상에 상단 여백이 전부 달라서 디자인 넘겨받은게 상단 여백이 기준이 되야 한다고 이해해서 저렇게 만들었네요. 중앙이 더 깔끔할 것 같다면 디자이너분과 다시 한 번 이야기 해 보는 것도 괜찮을 것 같다고 생각합니다!

2022-01-23 11:30 UTC, SolKimDev commented
수정사항 반영했습니다!

2022-01-23 13:32 UTC, blurfx approved these changes
고생하셨어요!

2022-01-23 13:57 UTC, merged